---
ID: "aa73be63-c2c1-4b28-a02d-54b0369a64e3"
Parent: "a30f65cc-dcf5-4769-8679-947561dca7ec"
Template: "04646a89-996f-4ee7-878a-ffdbf1f0ef0d"
Path: /sitecore/layout/Renderings/HCA/Feature/Catalog/Product Variants
DB: master
SharedFields:
- ID: "037fe404-dd19-4bf7-8e30-4dadf68b27b0"
  Hint: componentName
  Value: Product Variants
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180504T102854Z
