---
ID: "1c8d57c1-e884-48cc-9e45-e8472f07bd09"
Parent: "a30f65cc-dcf5-4769-8679-947561dca7ec"
Template: "04646a89-996f-4ee7-878a-ffdbf1f0ef0d"
Path: /sitecore/layout/Renderings/HCA/Feature/Catalog/Product Filters
DB: master
SharedFields:
- ID: "037fe404-dd19-4bf7-8e30-4dadf68b27b0"
  Hint: componentName
  Value: Product Filters
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180426T100032Z
