---
ID: "589d9c3f-2c0e-41c3-85cf-7e27efad39f3"
Parent: "d0466420-eeca-46a4-93b6-b17cc198e87b"
Template: "d0466420-eeca-46a4-93b6-b17cc198e87b"
Path: /sitecore/templates/HCA/Project/HCA/Pages/Cart/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180427T145356Z
