---
ID: "ef4e31c0-95db-4331-ad4f-55923704ce28"
Parent: "938f39ab-1217-4a06-9c0f-f53494433851"
Template: "938f39ab-1217-4a06-9c0f-f53494433851"
Path: /sitecore/templates/HCA/Project/HCA/Folders/Checkout Folder/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180504T144048Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
