---
ID: "ebac9f85-2b0b-4c12-8815-16b17323b15e"
Parent: "5dccb05c-59f3-4579-aea3-6e5dc934c7b0"
Template: "5dccb05c-59f3-4579-aea3-6e5dc934c7b0"
Path: /sitecore/templates/HCA/Feature/Navigation/Menu Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180428T091426Z
    - ID: "2f131184-e443-4376-94b3-2283d246d205"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
