---
ID: "6a6b7f2f-5dc3-4255-99f4-d32998f77cb2"
Parent: "5d7682df-27d9-4fc9-bb4e-7ac06d7bbd7c"
Template: "2c7e608f-5450-4f6c-a990-b53526e7d35f"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/HCA/Payment Configuration
DB: master
SharedFields:
- ID: "ee2d99c3-35c0-4467-8532-0e2aa960bb87"
  Hint: Payment Options
  Type: Multilist
  Value: |
    {0CFFAB11-2674-4A18-AB04-228B1F8A1DEC}
    {B5E5464E-C851-4C3C-8086-A4A874DD2DB0}
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Payment Configuration
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171123T164030Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
