---
ID: "f68bad05-9731-48fa-897a-8e0f0aff2fe3"
Parent: "41bec638-40fe-4a75-ace5-f3377299d8fa"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/HCA/Feature/Checkout/Abstract/_Checkout Step/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180504T135125Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
