---
ID: "c83654e6-71ef-436c-b369-248b68d97bb5"
Parent: "b678ecfb-87a3-4f27-b3fb-2877f332c950"
Template: "b678ecfb-87a3-4f27-b3fb-2877f332c950"
Path: /sitecore/templates/CommerceConnect/Sitecore Commerce/Commerce Control Panel/Shared Settings/Currency/Currency Settings Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{CD71E410-4C40-4CAD-ADE8-4E54A14B116A}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161128T115236Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
