---
ID: "f98a1351-0fac-45b6-9d09-1759c4992678"
Parent: "3c1584a1-d872-4ae8-a59e-4e30f1b4408e"
Template: "3c1584a1-d872-4ae8-a59e-4e30f1b4408e"
Path: /sitecore/templates/HCA/Foundation/Base/_SiteDataSources/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200803T002118Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
