---
ID: "7453d071-c010-488a-b0a0-6465d222ad2f"
Parent: "762364a6-3ccb-43d2-9acb-c889db0f7fcf"
Template: "762364a6-3ccb-43d2-9acb-c889db0f7fcf"
Path: "/sitecore/templates/CommerceConnect/Sitecore Commerce/Commerce Control Panel/Storefront Settings/Storefront/Configuration/Country-Region Configuration/__Standard Values"
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161213T111154Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
