---
ID: "80f2135c-c8e9-4d49-822c-3206ebe262ee"
Parent: "dd175921-1cb8-4008-a74a-4782d6f10018"
Template: "0437fee2-44c9-46a6-abe9-28858d9fee8c"
Path: /sitecore/templates/CommerceConnect/Sitecore Commerce/Commerce Control Panel/Storefront Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161129T093123Z
